name: "go-custom-github-action"
description: "Custom Github Action with Go"

inputs:
  message:
    description: "Accept input args"
    required: true
    
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.message }}