name: Jacked Action
on: [push, pull_request]
jobs:
  jacked:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Jacked Scan
      uses: carbonetes/jacked-action@v1.0.0
      with:
        directory: .
        fail-criteria: "high"
